name: Deploy to Azure

on:
  push:
    branches: [deploy/azure]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}

    steps:
      - uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login \
            --client-id "$AZURE_CLIENT_ID" \
            --federated-credential-provider "github" \
            --tenant-id "$AZURE_TENANT_ID"
        shell: bash

      - name: Provision and Deploy
        run: azd up --no-prompt
        env:
          AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}
          PB_ADMIN_EMAIL: ${{ secrets.PB_ADMIN_EMAIL }}
          PB_ADMIN_PASSWORD: ${{ secrets.PB_ADMIN_PASSWORD }}
          SHARED_AI_NAME: ${{ vars.SHARED_AI_NAME }}
          SHARED_LAW_NAME: ${{ vars.SHARED_LAW_NAME }}
          SHARED_OBS_RG: ${{ vars.SHARED_OBS_RG }}
          AZURE_RG_NAME: ${{ vars.AZURE_RG_NAME }}
          AZURE_STORAGE_NAME: ${{ vars.AZURE_STORAGE_NAME }}
